---
#
#
- debug:
    msg: "START {{ role_path.split('/')[-1] }}"

- include_tasks: generate_vmm_cfg.yml
  when: operation == "generate_vmm_cfg"

- include_tasks: copy_configs_vmm.yml
  when: operation == "copy_configs_vmm"

  #- include_tasks: install.yml
  #when: operation == "install"

- debug:
    msg: "END {{ role_path.split('/')[-1] }}"
