---
# file: roles/common/handlers/main.yml
- name: restart ntpd
  service:
    name: ntpd
    state: started
    enabled: True

- name: stop ntpd
  service:
    name: ntpd
    state: stopped
    enabled: False

- name: restart sshd
  service:
    name: sshd
    state: restarted
