---
#
#

- debug:
    msg: "START {{ role_path.split('/')[-1] }}"

- name: Get configured hostname
  shell: "cat /etc/hostname"
  changed_when: false
  register: etc_hostname

- name: Valid if hostname is properly configured
  shell: "[ \"$(hostname)\" == \"{{ etc_hostname.stdout }}\" ]"
  register: hostname_check
  changed_when: false
  failed_when:
    - "hostname_check.rc != 0"
    - "hostname_check.rc != 1"
  when: not ansible_check_mode

- name: Configure hostname
  shell: "hostname \"{{ etc_hostname.stdout }}\""
  register: hostname_set
  when: not ansible_check_mode and hostname_check.rc == 1

- name: Copy motd file
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0444

- meta: refresh_inventory

- debug:
    msg: "END {{ role_path.split('/')[-1] }}"
