---
#
#
- debug:
    msg: "START {{ role_path.split('/')[-1] }}"

- name: "Create device configuration file"
  template:
    src: demo_vmx.conf.j2
    dest: "{{ role_path }}/files/vmx_{{ groups['mx'][0] }}.conf"
  loop: "{{ instances.vMXs }}"

- name: Push vMX device configuration
  shell: "python ../scripts/junos_merge_config.py --device_ip {{ item.1 }} --cfg_file {{ role_path }}/files/vmx_{{ item.1 }}.conf"
  with_indexed_items:
    - "{{ groups['mx'] }}"

- debug:
    msg: "END {{ role_path.split('/')[-1] }}"

